- name: Playbook sample
  hosts: inventory_
  gather_facts: false
  tasks:
    - name: call role
      include_role:
        name: sample_role
        
    - name: call role
      include_role:
        name: sample_role_2
